### PR TITLE
Agnostic to Python versions.

### PR DESCRIPTION
**Pull request by sidcode**
Commented out *print* statements since they are present for reporting errors but don't contribute to the final build. Corrected the indentation as well. The plugin works really well.

### CODE REVIEW

**Comment by pe44** [comment]
This should be merged, as it doesn't even harm the python 2.7 build.

**Comment by davidgfnet** [comment]
Nope, this is not a fix, but a hack. I would be ok using print() and/or changing the python version, but commenting out stuff... come on, can do better!

**Comment by pe44** [comment]
There you go. Compiled for me.

**Comment by davidgfnet** [comment]
The fact that it "compiles" doesn't mean it's properly done.

**Comment by pe44** [comment]
I guess you understood that I was talking about the other merge request, which doesn't comment out any print() commands. There's no harm in merging it, so I don't see why you wouldn't.

**Pull request closed without merging**
